// import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
// import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
// import { CommonModule } from '@angular/common'; // Required for basic directives if needed
//
//
// @Component({
//   selector: 'app-demo',
//   standalone: true, // Key: This makes it a standalone component
//   imports: [CommonModule], // Import CommonModule for directives
//   template: `
//     <h2>Server Content Editor (Standalone Component)</h2>
//     <p>Click on the content below to start editing. Press Tab or click outside to save changes.</p>
//
//     <div
//       #editableContent
//       [innerHTML]="safeHtml"
//       contenteditable="true"
//       class="editor-container"
//       (blur)="onContentChange()">
//     </div>
//
//     <hr>
//     <h3>Latest Saved HTML Output:</h3>
//     <pre>{{ editedHtmlContent }}</pre>
//   `,
// })
// export class DemoComponent implements OnInit {
//
//   // 1. Raw HTML content received from the server (simulated)
//   rawHtmlContent: string = `
//     <style>
//     .editor-container {
//       border: 1px solid #ccc;
//       padding: 15px;
//       min-height: 100px;
//       margin-top: 10px;
//       background-color: #f9f9f9;
//     }
//     .editor-container:focus {
//       border-color: blue;
//       box-shadow: 0 0 5px rgba(0, 0, 255, 0.5);
//       outline: none; /* Remove default focus outline */
//     }
//     .my-table {
//       // border-collapse: collapse;
//       border: 1px solid black;
//       width: 100%;
//     }
//     .my-table th, .my-table td {
//       border: 1px solid #ddd;
//       padding: 12px;
//       text-align: left;
//     }
//     .highlight {
//       color: #e91e63; /* Pink */
//       font-weight: bold;
//     }
//
//     </style>
//     <table class="my-table">
//       <thead>
//         <tr><th>Product</th><th>Price</th><th>Status</th></tr>
//       </thead>
//       <tbody>
//         <tr>
//           <td><b>Premium Account</b></td>
//           <td><span class="highlight">$99.00</span></td>
//           <td>Active</td>
//         </tr>
//         <tr>
//           <td>Basic Tier</td>
//           <td>$19.00</td>
//           <td><span class="highlight-in-content">Pending</span></td>
//         </tr>
//       </tbody>
//     </table>
//     <p>This is a paragraph that you can edit. The <strong>bold</strong> and <em>italic</em> formatting will be preserved.</p>
//   `;
//
//   // 2. Safe version of the HTML, required for [innerHTML]
//   safeHtml!: SafeHtml;
//
//   // 3. Output content after editing
//   editedHtmlContent: string = '';
//
//   // ViewChild to get a reference to the editable <div> element
//   // The type assertion <HTMLDivElement> is good practice
//   @ViewChild('editableContent') editableContent!: ElementRef<HTMLDivElement>;
//
//   constructor(private sanitizer: DomSanitizer) {}
//
//   ngOnInit(): void {
//     // SECURITY STEP: Bypassing sanitization for trusted server HTML.
//     this.safeHtml = this.sanitizer.bypassSecurityTrustHtml(this.rawHtmlContent);
//     this.editedHtmlContent = this.rawHtmlContent; // Initialize the output
//   }
//
//   /**
//    * Called when the user leaves the editable div (on blur event).
//    * Captures the updated innerHTML of the div.
//    */
//   onContentChange(): void {
//     if (this.editableContent) {
//       // Get the current HTML content generated by the browser's editor
//       const updatedContent = this.editableContent.nativeElement.innerHTML;
//
//       this.editedHtmlContent = updatedContent;
//
//       console.log('✅ Content updated. New HTML:');
//       console.log(this.editedHtmlContent);
//
//       // TODO: Send 'this.editedHtmlContent' back to your server
//     }
//   }

// import { Component } from "@angular/core";
// import { OpeningParagraphComponent } from "../home/create-committee/opening-paragraph/opening-paragraph.component";
//
//
// // }
// @Component ({
//   selector: 'app-demo',
//   standalone:true,
//   imports: [OpeningParagraphComponent],
//   templateUrl: './demo.component.html',
//   styleUrl: './demo.component.scss'
// })
// export class DemoComponent {}

//CALENDAR

// import { Component, Input } from '@angular/core';
// import { NgFor, NgClass, NgIf } from '@angular/common';
// import { FormsModule } from '@angular/forms';
//
// @Component({
//   selector: 'app-demo',
//   standalone: true,
//   imports: [NgFor, NgClass, NgIf, FormsModule],
//   template: `
//     <div class="calendar-container">
//       <div class="header">
//         <label for="yearSelect">Select Year:</label>
//         <select id="yearSelect" [(ngModel)]="selectedYear">
//           <option *ngFor="let y of years" [value]="y">{{ y }}</option>
//         </select>
//       </div>
//
//       <div class="calendar">
//         <div class="month" *ngFor="let month of months">
//           <h3>{{ getMonthName(month) }}</h3>
//           <div class="days">
//             <div
//               class="day"
//               *ngFor="let day of getDaysInMonth(selectedYear, month)"
//               [ngClass]="{ meeting: isMeeting(day), today: isToday(day) }"
//             >
//               {{ day.getDate() }}
//             </div>
//           </div>
//         </div>
//       </div>
//     </div>
//   `,
//   styles: [`
//     .calendar-container {
//       padding: 1rem;
//       font-family: sans-serif;
//     }
//
//     .header {
//       display: flex;
//       align-items: center;
//       gap: 0.5rem;
//       margin-bottom: 1rem;
//     }
//
//     select {
//       padding: 0.25rem 0.5rem;
//       font-size: 14px;
//       border-radius: 4px;
//       border: 1px solid #ccc;
//       background: #fff;
//     }
//
//     .calendar {
//       display: grid;
//       grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
//       gap: 1rem;
//     }
//
//     .month {
//       border: 1px solid #ccc;
//       border-radius: 8px;
//       padding: 0.75rem;
//       text-align: center;
//       background: #fafafa;
//     }
//
//     .days {
//       display: grid;
//       grid-template-columns: repeat(7, 1fr);
//       gap: 4px;
//       margin-top: 0.5rem;
//     }
//
//     .day {
//       padding: 4px 0;
//       border-radius: 4px;
//       font-size: 12px;
//     }
//
//     .day.meeting {
//       background-color: #4caf50;
//       color: white;
//       font-weight: bold;
//     }
//
//     .day.today {
//       border: 1px solid #4caf50;
//       font-weight: bold;
//     }
//   `]
// })
// export class DemoComponent {
//   @Input() meetingDates: string[] = []; // Example: ['2025-03-14', '2024-05-02']
//
//   currentYear = new Date().getFullYear();
//   selectedYear = this.currentYear;
//   months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
//   years: number[] = [];
//
//   ngOnInit() {
//     // Determine range of years based on meetings + current year
//     const meetingYears = this.meetingDates
//       .map(dateStr => new Date(dateStr).getFullYear());
//     const minYear = Math.min(...meetingYears, this.currentYear - 2);
//     const maxYear = Math.max(...meetingYears, this.currentYear + 2);
//     this.years = Array.from({ length: maxYear - minYear + 1 }, (_, i) => minYear + i);
//   }
//
//   getMonthName(month: number): string {
//     return new Date(this.selectedYear, month).toLocaleString('default', { month: 'long' });
//   }
//
//   getDaysInMonth(year: number, month: number): Date[] {
//     const days: Date[] = [];
//     const date = new Date(year, month, 1);
//     while (date.getMonth() === month) {
//       days.push(new Date(date));
//       date.setDate(date.getDate() + 1);
//     }
//     return days;
//   }
//
//   isMeeting(date: Date): boolean {
//     return this.meetingDates.includes(date.toISOString().split('T')[0]);
//   }
//
//   isToday(date: Date): boolean {
//     const today = new Date();
//     return date.toDateString() === today.toDateString();
//   }
// }
//
