import { Component, ElementRef, input, ViewChild } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { RecognizeNepaliTextDirective } from '../../../../utils/recognize-nepali-text.directive';

@Component({
  selector: 'app-opening-paragraph',
  standalone: true,
  imports: [RecognizeNepaliTextDirective],
  templateUrl: './opening-paragraph.component.html',
  styleUrl: './opening-paragraph.component.scss'
})
export class OpeningParagraphComponent {
  openingParagraph = input.required<string>();
  content!: string;
  safeHtml!: SafeHtml;
  @ViewChild('editableContent') editableContent!: ElementRef<HTMLDivElement>;


  constructor(private sanitizer: DomSanitizer) {}


  ngOnInit(): void {
    // SECURITY STEP: Bypassing sanitization for trusted server HTML.
    this.content = this.openingParagraph();
    this.safeHtml = this.sanitizer.bypassSecurityTrustHtml(this.content);
  }

  onContentChange(): void {
    if (this.editableContent) {
      // Get the current HTML content generated by the browser's editor
      const updatedContent = this.editableContent.nativeElement.innerHTML;
      this.content = updatedContent;
    }
  }
}
